version: "3.9"

services:
  postgres:
    container_name: myPostgres
    image: "postgres:13.4-alpine3.14"
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
